groups:
  - name: Connection was slow
    rules:
      - alert: SlowConnection
        expr: probe_http_duration_seconds{phase="connect"} > 0.0015
        for: 3s
        labels:
          severity: warning
        annotations:
          summary: "Connection took more than 1.5 milliseconds"
